//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material_Design_Desktop_Concept.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Material_Design_Desktop_Concept.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Concept_Wall_1920 {
            get {
                object obj = ResourceManager.GetObject("Concept_Wall_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_060_Off_183189 {
            get {
                object obj = ResourceManager.GetObject("if_060_Off_183189", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_060_Off_183189_White {
            get {
                object obj = ResourceManager.GetObject("if_060_Off_183189_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_060_Off_183189_White_Sel {
            get {
                object obj = ResourceManager.GetObject("if_060_Off_183189_White_Sel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_47_111099 {
            get {
                object obj = ResourceManager.GetObject("if_47_111099", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_47_111099_White {
            get {
                object obj = ResourceManager.GetObject("if_47_111099_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_98_111048 {
            get {
                object obj = ResourceManager.GetObject("if_98_111048", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_98_111048_White {
            get {
                object obj = ResourceManager.GetObject("if_98_111048_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_account_circle_326497 {
            get {
                object obj = ResourceManager.GetObject("if_account_circle_326497", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_account_circle_326497_White {
            get {
                object obj = ResourceManager.GetObject("if_account_circle_326497_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_account_circle_326497_White_Sel {
            get {
                object obj = ResourceManager.GetObject("if_account_circle_326497_White_Sel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_bluetooth_326516 {
            get {
                object obj = ResourceManager.GetObject("if_bluetooth_326516", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_bluetooth_326516_White {
            get {
                object obj = ResourceManager.GetObject("if_bluetooth_326516_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_bluetooth_connected_326502 {
            get {
                object obj = ResourceManager.GetObject("if_bluetooth_connected_326502", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_bluetooth_connected_326502_White {
            get {
                object obj = ResourceManager.GetObject("if_bluetooth_connected_326502_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_bluetooth_disabled_326507 {
            get {
                object obj = ResourceManager.GetObject("if_bluetooth_disabled_326507", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_bluetooth_disabled_326507_White {
            get {
                object obj = ResourceManager.GetObject("if_bluetooth_disabled_326507_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_bluetooth_searching_326512 {
            get {
                object obj = ResourceManager.GetObject("if_bluetooth_searching_326512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_bluetooth_searching_326512_White {
            get {
                object obj = ResourceManager.GetObject("if_bluetooth_searching_326512_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_battery_90_48px_352044 {
            get {
                object obj = ResourceManager.GetObject("if_ic_battery_90_48px_352044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_battery_90_48px_352044_White {
            get {
                object obj = ResourceManager.GetObject("if_ic_battery_90_48px_352044_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_battery_alert_48px_352045 {
            get {
                object obj = ResourceManager.GetObject("if_ic_battery_alert_48px_352045", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_battery_alert_48px_352045_White {
            get {
                object obj = ResourceManager.GetObject("if_ic_battery_alert_48px_352045_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_battery_charging_full_48px_352052 {
            get {
                object obj = ResourceManager.GetObject("if_ic_battery_charging_full_48px_352052", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_battery_charging_full_48px_352052_White {
            get {
                object obj = ResourceManager.GetObject("if_ic_battery_charging_full_48px_352052_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_battery_std_48px_352053 {
            get {
                object obj = ResourceManager.GetObject("if_ic_battery_std_48px_352053", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_battery_std_48px_352053_White {
            get {
                object obj = ResourceManager.GetObject("if_ic_battery_std_48px_352053_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_network_wifi_48px_352564 {
            get {
                object obj = ResourceManager.GetObject("if_ic_network_wifi_48px_352564", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_signal_wifi_1_bar_48px_352128 {
            get {
                object obj = ResourceManager.GetObject("if_ic_signal_wifi_1_bar_48px_352128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_signal_wifi_1_bar_48px_352128_White {
            get {
                object obj = ResourceManager.GetObject("if_ic_signal_wifi_1_bar_48px_352128_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_signal_wifi_4_bar_48px_352129 {
            get {
                object obj = ResourceManager.GetObject("if_ic_signal_wifi_4_bar_48px_352129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_signal_wifi_4_bar_48px_352129_White {
            get {
                object obj = ResourceManager.GetObject("if_ic_signal_wifi_4_bar_48px_352129_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_signal_wifi_off_48px_352130 {
            get {
                object obj = ResourceManager.GetObject("if_ic_signal_wifi_off_48px_352130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_signal_wifi_off_48px_352130_White {
            get {
                object obj = ResourceManager.GetObject("if_ic_signal_wifi_off_48px_352130_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_wifi_lock_48px_352226 {
            get {
                object obj = ResourceManager.GetObject("if_ic_wifi_lock_48px_352226", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_ic_wifi_lock_48px_352226_White {
            get {
                object obj = ResourceManager.GetObject("if_ic_wifi_lock_48px_352226_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_icon_bluetooth_211632 {
            get {
                object obj = ResourceManager.GetObject("if_icon_bluetooth_211632", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_icon_bluetooth_211632_White {
            get {
                object obj = ResourceManager.GetObject("if_icon_bluetooth_211632_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_lock__private__privacy__protection_2538743 {
            get {
                object obj = ResourceManager.GetObject("if_lock__private__privacy__protection_2538743", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_lock__private__privacy__protection_2538743_White {
            get {
                object obj = ResourceManager.GetObject("if_lock__private__privacy__protection_2538743_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_settings_bluetooth_326694 {
            get {
                object obj = ResourceManager.GetObject("if_settings_bluetooth_326694", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_settings_bluetooth_326694_White {
            get {
                object obj = ResourceManager.GetObject("if_settings_bluetooth_326694_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_share4_216719 {
            get {
                object obj = ResourceManager.GetObject("if_share4_216719", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap if_share4_216719_White {
            get {
                object obj = ResourceManager.GetObject("if_share4_216719_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-align: center;&quot;&gt;&lt;img src=&quot;Logo_128_Chrom&quot; width=&quot;128&quot; height=&quot;128&quot; /&gt;&lt;/p&gt;
        ///&lt;h2 style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;No Data&lt;/strong&gt;&lt;/h2&gt;.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_128_Chrom {
            get {
                object obj = ResourceManager.GetObject("Logo_128_Chrom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TrapApps {
            get {
                object obj = ResourceManager.GetObject("TrapApps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TrayApps {
            get {
                object obj = ResourceManager.GetObject("TrayApps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TrayAppsInactive {
            get {
                object obj = ResourceManager.GetObject("TrayAppsInactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TrayPanelAudio {
            get {
                object obj = ResourceManager.GetObject("TrayPanelAudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TrayPanelNotif {
            get {
                object obj = ResourceManager.GetObject("TrayPanelNotif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TrayPanelNotifSel {
            get {
                object obj = ResourceManager.GetObject("TrayPanelNotifSel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TraySel {
            get {
                object obj = ResourceManager.GetObject("TraySel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
